version: 0.2

phases:
  pre_build:
    commands:
      - npm i -g @nestjs/cli  
      - npm i -g rimraf
      - npm i
      - npm run prebuild
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'dist'